apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: ${Cluster-name}
  region: us-west-2
  version: "1.23"
  tags:
    karpenter.sh/discovery: ${Cluster-name}

managedNodeGroups:
  - name: application-a-ng
    instanceType: m5.large
    minSize: 2
    maxSize: 5
    desiredCapacity: 2
    privateNetworking: true # if only 'Private' subnets are given, this must be enabled
    labels: {app/team: application-a}
    updateConfig:	
      maxUnavailable: 2
  - name: application-b-ng
    instanceType: m5.large
    minSize: 2
    maxSize: 5
    desiredCapacity: 2
    privateNetworking: true # if only 'Private' subnets are given, this must be enabled
    labels: {app/team: application-b}
    updateConfig:
      maxUnavailable: 2
iam:
  withOIDC: true