apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: application-a-provisioner
spec:
  requirements:
   - key: node.kubernetes.io/instance-type
     operator: In
     values: ["m5.large", "m5.xlarge"]
  taints:
    - key: app/team
      value: application-b
      effect: NoSchedule
  labels:
    app/team: application-b
  
  ttlSecondsAfterEmpty: 600
  provider:
    subnetSelector:
      karpenter.sh/discovery: ${CLUSTER_NAME}
    securityGroupSelector:
      karpenter.sh/discovery: ${CLUSTER_NAME}
    instanceProfile: KarpenterNodeInstanceProfile-${CLUSTER_NAME}
